//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competidores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competidores()
        {
            this.Despesas = new HashSet<Despesas>();
            this.Frequencias = new HashSet<Frequencias>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public byte[] Foto { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> Nascimento { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despesas> Despesas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Frequencias> Frequencias { get; set; }
    }
}
