//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despesas
    {
        public int Id { get; set; }
        public Nullable<int> IdTipoDespesa { get; set; }
        public Nullable<int> IdCompetidor { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Competidores Competidores { get; set; }
        public virtual TiposDespesa TiposDespesa { get; set; }
    }
}
