//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int Id { get; set; }
        public int IdExpenseType { get; set; }
        public int IdCompetitor { get; set; }
        public int Value { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Competitors Competitors { get; set; }
        public virtual ExpenseTypes ExpenseTypes { get; set; }
    }
}
