//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frequency
    {
        public int Id { get; set; }
        public Nullable<int> IdCompetitor { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
    
        public virtual Competitors Competitors { get; set; }
    }
}
