//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Competidores = new HashSet<Competidores>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTipoUsuario { get; set; }
        public Nullable<int> IdEscola { get; set; }
        public Nullable<int> IdModalidade { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competidores> Competidores { get; set; }
        public virtual Escola Escola { get; set; }
        public virtual Modalidades Modalidades { get; set; }
        public virtual TiposUsuario TiposUsuario { get; set; }
    }
}
